name: Generate Tomorrow's Horoscopes

on:
  schedule:
    # 00:00 Israel time (UTC+3 during DST, UTC+2 during Standard)
    - cron: "0 21 * * *"  # 00:00 IDT (March-October)
    - cron: "0 22 * * *"  # 00:00 IST (October-March)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci || npm install
      
      - name: Generate tomorrow's horoscopes
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run gen:tomorrow
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add daily/*.json
          git diff --staged --quiet || (git commit -m "Generate horoscopes for tomorrow [skip ci]" && git push)